// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todo.Models;

#nullable disable

namespace todo.Migrations
{
    [DbContext(typeof(JegyzetekDbContext))]
    [Migration("20241024111524_sqlite.local_migration_753")]
    partial class sqlitelocal_migration_753
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("todo.Models.Jegyzet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("kartyaID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("kesz")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("letrehozasIdeje")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("modositasIdeje")
                        .HasColumnType("TEXT");

                    b.Property<string>("tartalom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jegyzet");
                });

            modelBuilder.Entity("todo.Models.Kartya", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Kartya");
                });
#pragma warning restore 612, 618
        }
    }
}
